In [1]:
!pip install yfinance
!pip install pandas_datareader

Requirement already satisfied: yfinance in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (1.3.0)
Requirement already satisfied: pandas>=1.3.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2.3.4)
Requirement already satisfied: requests>=2.31 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2.33.1)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (4.9.6)
Requirement already satisfied: pytz>=2022.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (4.0.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (7.34.1)
Requirement already satisfied: websockets>=13.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.4.22)
Requirement already satisfied: rich in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.31->yfinance) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.31->yfinance) (2.6.3)
Requirement already satisfied: pycparser in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas_datareader in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (0.10.0)
Requirement already satisfied: lxml in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas_datareader) (6.1.0)
Requirement already satisfied: pandas>=0.23 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas_datareader) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas_datareader) (2.33.1)
Requirement already satisfied: numpy>=1.23.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2026.4.22)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

import yfinance as yf
yf.pdr_override()

AttributeError: module 'yfinance' has no attribute 'pdr_override'

In [ ]:
PG = wb.DataReader('PG', start='1995-1-1')

[*********************100%%**********************]  1 of 1 completed

In [ ]:
PG.head()

                Open      High       Low     Close  Adj Close   Volume
Date
1995-01-03  15.46875  15.62500  15.43750  15.59375   7.529935  3318400
1995-01-04  15.53125  15.65625  15.31250  15.46875   7.469574  2218800
1995-01-05  15.37500  15.43750  15.21875  15.25000   7.363945  2319600
1995-01-06  15.15625  15.40625  15.15625  15.28125   7.379035  3438000
1995-01-09  15.34375  15.40625  15.18750  15.21875   7.348854  1795200

In [ ]:
PG.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-04-18,156.339996,157.630005,155.960007,157.289993,157.289993,7819300
2024-04-19,154.979996,158.179993,153.520004,158.139999,158.139999,12028400
2024-04-22,158.429993,161.289993,157.250000,160.539993,160.539993,8926300
2024-04-23,161.679993,162.100006,160.419998,161.500000,161.500000,7707300
2024-04-24,161.199997,162.860001,159.419998,162.600006,162.600006,7216600

## Simple Rate of Return

$$
\frac{P_1 - P_0}{P_0} = \frac{P_1}{P_0} - 1
$$

In [ ]:
PG['simple_return'] = (PG['Adj Close'] / PG['Adj Close'].shift(1)) - 1
print (PG['simple_return'])

Date
1995-01-03         NaN
1995-01-04   -0.008016
1995-01-05   -0.014141
1995-01-06    0.002049
1995-01-09   -0.004090
                ...
2024-04-18    0.008573
2024-04-19    0.005404
2024-04-22    0.015176
2024-04-23    0.005980
2024-04-24    0.006811
Name: simple_return, Length: 7379, dtype: float64